### ISSUE TITLE
Not working with logstash 6.X

### ISSUE THREAD

**Issue by dhpowrhost** [whyscream/postfix-grok-patterns#132]
After upgrading to Logstash 6 this does not work anymore :(
Can anyone help me find a way to get it working again?

**Comment by whyscream** [comment]
Can you please describe what is not working? how do messages look in logstash after the filtering is applied?

**Comment by dhpowrhost** [comment]
I also use the syslog filter and it is only the syslog-filter that works. All the postfix patterns are added in runtime, but for some reason never validated.. Have you test with version 6?

**Comment by dhpowrhost** [comment]
The output is like this:
`[2018-11-07T14:19:20,734][DEBUG][logstash.pipeline        ] filter received {"event"=>{"@timestamp"=>2018-11-07T14:19:11.912Z, "beat"=>{"version"=>"5.6.12", "hostname"=>"mailscanner2", "name"=>"mailscanner2"}, "@version"=>"1", "offset"=>394779217, "input_type"=>"log", "source"=>"/var/log/mail.log", "host"=>"mailscanner2", "tags"=>["beats_input_codec_plain_applied"], "message"=>"Nov  7 15:11:04 mailscanner2.powerhosting.dk postfix/smtpd[14945]: 42qpHD5Rpwz12Ms: client=unknown[152.115.128.162], sasl_method=PLAIN, sasl_username=jc@johannestorpe.com", "type"=>"syslog"}}

[2018-11-07T14:19:20,739][DEBUG][logstash.filters.grok    ] Running grok filter {:event=>#<LogStash::Event:0x60ee6d99>}
[2018-11-07T14:19:20,739][DEBUG][logstash.util.decorators ] filters/LogStash::Filters::Grok: adding value to field {"field"=>"received_at", "value"=>["%{@timestamp}"]}
[2018-11-07T14:19:20,739][DEBUG][logstash.util.decorators ] filters/LogStash::Filters::Grok: adding value to field {"field"=>"received_from", "value"=>["%{host}"]}
`
As you see the postfix fields are not recognised.

**Comment by whyscream** [comment]
THe log sample seems to indicate that the message field is filled wit hthe complete log line from syslog, including the date(`Nov  7 15:11:04`), hostname (`mailscanner2.powerhosting.dk`) and program (`postfix/smtpd[14945]`) data. This means that you first need to apply the syslog parser onto this input, so you'll have the correct data in the fields `program` and `message`.

The reason that the postfix filter is never applied is because it needs both of these fields, and the `program` field never exists in your current setup (and the message field has the wrong data too).
