### ISSUE TITLE
Excess postfix_ fields created by unicode email subject lines

### ISSUE THREAD

**Issue by eik3** [whyscream/postfix-grok-patterns#99]
Thanks for this great set of patterns+config, it's already successfully parsing millions of postfix log lines per day!

Unfortunately, there seems to be an issue with non-ascii email subject lines like "Grüße ‒ test":

When parsing this line

`Dec 14 11:52:17 mail.example.com postfix/cleanup[20534]: D95341E50350: info: header Subject: =?utf-8?Q?Gr=C3=BC=C3=9Fe?= =?utf-8?Q?_=E2=80=92?= test from local; from=<from@example.com> to=<to@example.com>`

The result in ES looks like this:
![selection_20161214_1530x289_001](https://cloud.githubusercontent.com/assets/17581/21181426/2c10bf7e-c1fe-11e6-82a0-79435da0eeb1.png)

The problem is that it causes thousands of `postfix_` fields.

**Comment by whyscream** [comment]
@eik3 would the changes in #100 solve your issue?

**Comment by whyscream** [comment]
FYI: This obsoletes the field `postfix_warning`, and adds the fields `postfix_message` and `postfix_message_level`. The results for your example are shown in  https://github.com/whyscream/postfix-grok-patterns/blob/42de9f178c6a047212a12053a85822eb6a154a83/test/cleanup_0007.yaml

**Comment by eik3** [comment]
Thank you @whyscream for the super fast fix, it works like a charm!

**Comment by eik3** [comment]
I've found a very similar case where the pattern created excess fields.

When a file named 

`INVOICE_ö_ä_ü_€_dhkfjs_jdofkajsldkfj_lsjdalkfjh_adjkfsahfdjk_Grüße_ihkfhsakj_dfahs_dfkjahskdhf_ksajh_dkfjhakshd_fasdfh_ksajhdfkljhsosid_fklsdfhhsdkl.pdf` 

is sent, this is how the postfix log line looks like:

`413E164734: info: header Content-Disposition: attachment;? filename="=?UTF-8?B?SU5WT0lDRV/Dtl/DpF/DvF/igqxfZGhrZmpzX2pkb2ZrYWpzbGRrZmpfbHNq?= =?UTF-8?B?ZGFsa2ZqaF9hZGprZnNhaGZkamtfR3LDvMOfZV9paGtmaHNha2pfZGZhaHNf?= =?UTF-8?B? from localhost[127.0.0.1]; from=<from@example.com> to=<to@example.com> proto=ESMTP helo=<localhost.localdomain>`

I don't really understand how the filename is truncated and split into several `?UTF-8?B?` blocks, but it seems to confuse the pattern:

![image](https://cloud.githubusercontent.com/assets/17581/21614512/fe1c85f8-d1d9-11e6-97af-d34e734ad16f.png)

**Comment by whyscream** [comment]
The problem is in the fact the semicolon (`;`) in `attachment;?`. The pattern believes that the separator between the random data in the first part of the line and the structured key-value pairs at the end of the line (starting with `from=<...>`) is a semicolon. Unfortunately there is semicolon in the random data (this can happen when logging subjects and other untrusted input data too of course), so the pattern breaks.

**Comment by whyscream** [comment]
The change #103 solves this issue, but there's still room for breakage: in order to detect the separation between key value data and other stuff, we need to set some limits on what data can be expected where. When postfix generates this data, we can predict the outcome, but for untrusted input (i.e. from external sources such as sender addresses, helo strings, messages headers etc) this is impossible.
